config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :categories do
    resources :products
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def new
    @category = Category.new
  end

  def destroy
    get_category_by_id
    @category.destroy

    redirect_to categories_path
  end

  def edit
    get_category_by_id
  end

  def update
    get_category_by_id

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    get_category_by_id
  end

  private
  def get_category_by_id
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", only: :destroy

  def create
    get_category_by_id
    make_comment_from_params
    redirect_to category_path(@category)
  end

  def destroy 
    get_category_by_id
    @comment = @category.comments.find(params[:id])
    @comment.destroy
    redirect_to category_path(@category)
  end

  private
  def make_comment_from_params
    @comment = @category.comments.create(comment_params)
  end

  def get_category_by_id
    @category = Category.find(params[:category_id])
  end

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", only: :destroy

  def create
    get_category_by_id
    make_product_from_params
    redirect_to category_path(@category)
  end

  def destroy 
    get_category_by_id
    find_product
    @product.destroy
    redirect_to category_path(@category)
  end

  def show
    get_category_by_id
    find_product
  end

  private
  def find_product
    @product = @category.products.find(params[:id])
  end

  def make_product_from_params
    @product = @category.products.create(product_params)
  end

  def get_category_by_id
    @category = Category.find(params[:category_id])
  end

  def product_params
    params.require(:product).permit(:developer, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <%= render 'error' %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/_error.html.erb
<% if @category.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@category.errors.count, "error") %> prohibited
    this category from being saved:</h2>
  <ul>
  <% @category.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= render 'error' %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %> 
 
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<body role="document">
  <div class="container" role="main">
    <div class="page-header">
      <h1>Listing Categories</h1>
    </div>

    <p>
      <%= link_to 'New category', new_category_path %>
    </p>

    <table class="table">
      <thread>
        <tr>
          <th>Category</th>
          <th>Description</th>
        </tr>
      </thread>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.title %></td>
            <td><%= category.text %></td>
            <td><%= link_to 'Show', category_path(category) %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p>
      <%= link_to 'Back', controller: 'welcome' %>
    </p>
  </div>
</body>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %> 

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<body role="document">
  <div class="container" role="main">
    <div class="page-header">
      <h2>Products:</h2>
      <p>
        <%= @category.title %>
      </p>
    </div>

    <table class="table">
      <thread>
        <tr>
          <th>Product</th>
          <th>Created by:</th>
        </tr>
      </thread>

      <tbody>
        <% @category.products.each do |product| %>
          <tr>
            <td><%= product.body %></td>
            <td><%= product.developer %></td>
            <td><%= link_to 'Show', category_product_path(@category, product) %>
            <td><%# link_to 'Edit', edit_product_path(category) %></td>
            <td><%# link_to 'Destroy', product_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="page-header">
      <h2>Add a product:</h2>
      <p>
        <%= render "products/form" %>
      </p>
    </div>

    <p>
      <%= link_to 'Back', categories_path %> | 
      <%= link_to 'Edit', edit_category_path %>
    </p>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoreFront</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for([@category, @category.products.build]) do |f| %>
  <p>
    <%= f.label :developer %><br>
    <%= f.text_field :developer %>
  </p>
  <p>
    <%= f.label :product %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </P>
<% end %>

app/views/products/_product.html.erb
<body role="document">
  <div class="container" role="main">
    <div class="page-header">
      <h2>Product:</h2>
    </div>

    <p>
      <strong>Developed by:</strong>
      <%= product.developer %>
    </p>
    <p>
      <strong>Software:</strong>
      <%= product.body %>
    </p>

    <p>
      <%= link_to 'Back', categories_path %> | 
      <%= link_to 'Destroy', [product.category, product], method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
</body>

app/views/products/show.html.erb
<%= render partial: 'product', locals: {product: @product} %>

app/views/welcome/index.html.erb
<body role="document">
  <div class="container" role="main">
    <div class="page-header">
      <h1>Software Store</h1>
    </div>

    <p>
      <%= link_to 'Catalog', controller: 'categories' %>
    </p>
  </div>
</body>